# Generated by Django 4.2.4 on 2023-08-27 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "dni",
                    models.CharField(max_length=10, unique=True, verbose_name="DNI"),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
                ("age", models.PositiveIntegerField(default=0, verbose_name="Edad")),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                ("state", models.BooleanField(default=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatar/%Y/%m/%d"
                    ),
                ),
                ("cvitae", models.FileField(upload_to="cvitae/%Y/%m/%d")),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "Empleado",
                "ordering": ["id"],
            },
        ),
    ]
