# Generated by Django 4.2.4 on 2023-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_employee_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(default="", max_length=50),
        ),
    ]
