# Generated by Django 4.2.4 on 2023-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_type_employee_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="categorys",
            field=models.ManyToManyField(to="app.category", verbose_name="Categoría"),
        ),
    ]
