# Generated by Django 4.2.4 on 2023-08-27 23:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_employee_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "dni",
                    models.CharField(max_length=10, unique=True, verbose_name="DNI"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
                ("sexo", models.CharField(blank=True, max_length=30, null=True)),
                ("address", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DetailSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio",
                    ),
                ),
                ("cant", models.IntegerField(default=0.0, verbose_name="Cantidad")),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Subtotal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Venta",
                "verbose_name_plural": "Detalle Ventas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("image", models.ImageField(upload_to="", verbose_name="Imagen")),
                (
                    "pvp",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(default=datetime.datetime.now)),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=9, verbose_name="IVA"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Total",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["id"],
            },
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
        migrations.AddField(
            model_name="detailsale",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AddField(
            model_name="detailsale",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.sale",
                verbose_name="venta",
            ),
        ),
    ]
