# Generated by Django 4.2.4 on 2023-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_client_detailsale_product_sale_delete_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/img/productos/",
                verbose_name="Imagen",
            ),
        ),
    ]
