# Generated by Django 4.2.4 on 2023-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=350, null=True, verbose_name="Descripción"
            ),
        ),
    ]
