# Generated by Django 4.2.4 on 2023-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
        ),
    ]
